name: compmedar
description: "Human Anatomy Learning and Assessment App with AR"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.5.3 <4.1.0" # Adjust based on your Flutter SDK

dependencies:
  flutter:
    sdk: flutter
  firebase_messaging: ^15.2.3
  firebase_core: ^3.2.0
  firebase_auth: ^5.1.2
  cloud_firestore: ^5.1.0
  firebase_database: ^11.0.3
  firebase_storage: ^12.1.1
  cloud_functions: ^5.0.3
  firebase_analytics: ^11.2.0
  google_sign_in: ^6.2.1
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  image_picker: ^1.1.2
  permission_handler: ^11.3.1
  image_cropper: ^8.0.2
  flutter_image_compress: ^2.3.0
  path_provider: ^2.1.4
  path: ^1.0.0
  qr_code_scanner: ^1.0.1
  url_launcher: ^6.2.5
  webview_flutter: ^4.9.0
  model_viewer_plus: ^1.9.1
  shared_preferences: ^2.0.15
  arcore_flutter_plugin: ^0.1.0
  intl: ^0.18.0
  google_api_availability: ^5.0.0
  http: ^1.2.2
  file_picker: ^9.0.0
  dropdown_button2: ^2.1.0
  video_player: ^2.7.0
  shared_preferences_android: ^2.4.6
  flutter_launcher_icons: ^0.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  assets:
    - assets/google_logo.png
    - assets/default_profile.png
    - assets/organs.png
    - assets/skeletal.png
    - assets/3d_quiz.html
    - assets/background_image.png
    - assets/icon2.png
    - assets/medical_background.png
    - assets/news_placeholder1.png
    - assets/news_placeholder2.png

  uses-material-design: true

flutter_icons:
  android: true
  image_path: "assets/icon.png"
